name: Test Pipeline

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Build
        run: |
          echo "this is Surya Bhaskar"

  final:
    runs-on: self-hosted
    steps:
      - name: Final
        run: |
          echo "This is Final"
